version: "3"

services:
  app:
    build: ./
    command: rails s
    ports:
      - "3000:3000"
    environment:
      GOSLAR_DATABASE_PASSWORD: s3creT@
      GOSLAR_DATABASE_HOST: db

  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goslar
      POSTGRES_PASSWORD: s3creT@
