default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("GOSLAR_DATABASE_HOST") { "localhost" } %>
  password: <%= ENV.fetch("GOSLAR_DATABASE_PASSWORD") %>
  port: 5432
  username: goslar

development:
  <<: *default
  database: goslar_development

test:
  <<: *default
  database: goslar_test

production:
  <<: *default
  database: goslar_production
